name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'   # runs every day at midnight
  workflow_dispatch:        # lets you run it manually too

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
